export const light = {
  '.cingopablo-light': {
    '--color-primary': 'hsl(var(--palette-purple-600))',
    '--color-primary-emphasis': 'hsl(var(--palette-purple-500))',
    '--color-primary-clear': 'hsl(var(--palette-purple-100))',
    '--color-header': 'hsl(var(--palette-gray-20) / 60%)',
    '--color-background': 'hsl(var(--palette-gray-20))',
    '--color-background-overlay': 'hsl(var(--palette-gray-00))',
    '--color-text-primary': 'hsl(var(--palette-purple-900))',
    '--color-text-secondary': 'hsl(var(--palette-gray-600))',
    '--color-text-tertiary': 'hsl(var(--palette-gray-400))',
    '--color-info': 'hsl(var(--palette-blue-500))',
    '--color-info-emphasis': 'hsl(var(--palette-blue-350))',
    '--color-info-clear': 'hsl(var(--palette-blue-100))',
    '--color-success': 'hsl(var(--palette-green-500))',
    '--color-success-emphasis': 'hsl(var(--palette-green-350))',
    '--color-success-clear': 'hsl(var(--palette-green-100))',
    '--color-warning': 'hsl(var(--palette-orange-500))',
    '--color-warning-emphasis': 'hsl(var(--palette-orange-350))',
    '--color-warning-clear': 'hsl(var(--palette-orange-100))',
    '--color-danger': 'hsl(var(--palette-red-550))',
    '--color-danger-emphasis': 'hsl(var(--palette-red-350))',
    '--color-danger-clear': 'hsl(var(--palette-red-100))',
    '--color-shadow': 'var(--palette-purple-500)',
    '--color-shadow-info': 'var(--palette-blue-500)',
    '--color-shadow-success': 'var(--palette-green-500)',
    '--color-shadow-warning': 'var(--palette-orange-500)',
    '--color-shadow-danger': 'var(--palette-red-550)',
    '--code-surface-1': 'var(--color-background-overlay)',
    '--code-surface-2': 'hsl(var(--palette-gray-200) / 20%)',
    '--code-surface-3': 'hsl(var(--palette-purple-20))',
    '--code-surface-error': 'hsl(var(--palette-red-100))',
    '--code-comment': 'var(--color-text-tertiary)',
    '--code-selector': 'hsl(var(--palette-green-500))',
    '--code-symbol': 'hsl(var(--palette-blue-350))',
    '--code-operator': 'hsl(var(--palette-red-100))',
    '--code-keyword': 'hsl(var(--palette-purple-300))',
    '--code-function': 'hsl(var(--palette-orange-350))',
    '--code-punctuation': 'hsl(var(--palette-blue-100))',
  },
}
