export const colors = {
  /* Gray scale */
  '--base-gray': '180deg 2%',
  '--palette-gray-00': 'var(--base-gray) 100%',
  '--palette-gray-20': 'var(--base-gray) 98%',
  '--palette-gray-50': 'var(--base-gray) 95%',
  '--palette-gray-100': 'var(--base-gray) 90%',
  '--palette-gray-200': 'var(--base-gray) 80%',
  '--palette-gray-300': 'var(--base-gray) 70%',
  '--palette-gray-400': 'var(--base-gray) 60%',
  '--palette-gray-500': 'var(--base-gray) 50%',
  '--palette-gray-600': 'var(--base-gray) 40%',
  '--palette-gray-700': 'var(--base-gray) 30%',
  '--palette-gray-800': 'var(--base-gray) 20%',
  '--palette-gray-900': 'var(--base-gray) 10%',
  // Base Purple
  '--base-purple': '243deg 75%',
  '--palette-purple-20': 'var(--base-purple) 98%',
  '--palette-purple-50': 'var(--base-purple) 95%',
  '--palette-purple-100': 'var(--base-purple) 90%',
  '--palette-purple-200': 'var(--base-purple) 80%',
  '--palette-purple-300': 'var(--base-purple) 70%',
  '--palette-purple-400': 'var(--base-purple) 60%',
  '--palette-purple-500': 'var(--base-purple) 50%',
  '--palette-purple-600': 'var(--base-purple) 40%',
  '--palette-purple-750': 'var(--base-purple) 25%',
  '--palette-purple-850': 'var(--base-purple) 15%',
  '--palette-purple-900': 'var(--base-purple) 10%',
  /* Blue scale */
  '--base-blue': '211deg 100%',
  '--palette-blue-100': 'var(--base-blue) 90%',
  '--palette-blue-350': 'var(--base-blue) 65%',
  '--palette-blue-500': 'var(--base-blue) 50%',
  '--palette-blue-700': 'var(--base-blue) 30%',
  '--palette-blue-800': 'var(--base-blue) 20%',
  /* Green scale */
  '--base-green': '135deg 59%',
  '--palette-green-100': 'var(--base-green) 90%',
  '--palette-green-350': 'var(--base-green) 65%',
  '--palette-green-500': 'var(--base-green) 50%',
  '--palette-green-700': 'var(--base-green) 30%',
  '--palette-green-800': 'var(--base-green) 20%',
  /* Orange scale */
  '--base-orange': '35deg 100%',
  '--palette-orange-100': 'var(--base-orange) 90%',
  '--palette-orange-350': 'var(--base-orange) 65%',
  '--palette-orange-500': 'var(--base-orange) 50%',
  '--palette-orange-700': 'var(--base-orange) 30%',
  '--palette-orange-800': 'var(--base-orange) 20%',
  /* Red scale */
  '--base-red': '3deg 100%',
  '--palette-red-100': 'var(--base-red) 90%',
  '--palette-red-350': 'var(--base-red) 65%',
  '--palette-red-500': 'var(--base-red) 50%',
  '--palette-red-550': 'var(--base-red) 45%',
  '--palette-red-700': 'var(--base-red) 30%',
  '--palette-red-800': 'var(--base-red) 20%',
}
